### ISSUE TITLE
Platfomio project tasks missing 

### ISSUE THREAD

**Issue by Trilis29** [Gifford47/HCPBridgeMqtt#29]
**Describe the bug**
I can only see esp32s3 build flags, how to build for casual espp32?

**Comment by Trilis29** [comment]
for line 11 in platformio.ini I have modified
`[env:esp32]`

**Comment by 14yannick** [comment]
Or use the master branch

**Comment by Trilis29** [comment]
Ahhh yes 😀 but stil maybe should be commited so that esp32 goes by default also

**Comment by Trilis29** [comment]
If you choose default it builds all except default 😊

**Comment by jkaberg** [comment]
> You can just click the default build target, that should use ep32 as well as the sensor only targets without the s3 prefix

Doesn't apply for us that doesn't use VSC 😄 We need to modify the .ini and add an additional environment as it sits, easy fix tho

**Comment by Tysonpower** [comment]
Adde the esp32 target back, see Pull Request #35
