### ISSUE TITLE
The naming of MQTT entities since Home Assistant 2023.8.0

### ISSUE THREAD

**Issue by apromix** [Gifford47/HCPBridgeMqtt#30]
Hi everybody!

At first many thanks for this project!

Today I updated HA and saw this warnings:

![image](https://github.com/Gifford47/HCPBridgeMqtt/assets/4678099/921b7c3d-7189-4fdb-abbd-cb6cf7da52a9)
![image](https://github.com/Gifford47/HCPBridgeMqtt/assets/4678099/65e88d61-9e66-46a5-846f-37f0442d3e5e)

More info here:
https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

So small fix of MQTT entries is needed.

Have a nice day!

**Comment by shellyeah** [comment]
Changing the value in [Line 11 in the configuration.h](https://github.com/Gifford47/HCPBridgeMqtt/blob/fe5e4b99b7eb255004075ceb5607656305a45bd6/HCPBridgeESP32/src/configuration.h#L11) (#define DEVICE_ID) to something other than garage_door should do the trick.

**Comment by 14yannick** [comment]
Temporary fix is in development branch. Has to ne considered in new preferences implementation
https://github.com/Gifford47/HCPBridgeMqtt/discussions/20
