### ISSUE TITLE
WifiHotsopot does not close 

### ISSUE THREAD

**Issue by fisch55** [Gifford47/HCPBridgeMqtt#59]
Today I noticed that the WifiHotspot does not close after the HomeAssistant configuration, which is a security risk as anyone can connect to the hotspot and open the gate.

Everything works fine, except for the fact that you can connect to the HCPBridge and end up on the Garagentor page...

Did I do something wrong?

Useing Release: 0.0.6.1

**Comment by Gifford47** [comment]
Please try to disable the AP in the UI. It's under basic configuration -> enable WiFi ap

**Comment by fisch55** [comment]
Great - No Bug . 
Thx for your WORK and HELP!!

Issue can be closed 🙈

**Comment by fisch55** [comment]
My fault … No Bug!!!
