### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by mic9119** [Gifford47/HCPBridgeMqtt#61]
Is there chance to get the temperature from the dht sensor in the /status page?

**Comment by Gifford47** [comment]
Yes, I'm already working on it...

**Comment by Gifford47** [comment]
Look at the latest dev version. Temperature and humidity are shown in the UI if sensor is available. It's the first iteration for the UI. If i have time enough I'll rework the display setting.

**Comment by mic9119** [comment]
Hey,
i flashed my ESP32 in my office. The esp in not connected to the drive. I get the following picture:
![garage](https://github.com/Gifford47/HCPBridgeMqtt/assets/95573134/17a7555e-2c05-44ae-99e3-5a5091f034bc)

**Comment by Gifford47** [comment]
look at system infomation->door status. do you get a json with "temp" attribute? if yes, please press F12 (on desktop chrome browser), reload the page and look if there's an extra section before the door buttons.
