### ISSUE TITLE
Issue when choosing ESP Model 

### ISSUE THREAD

**Issue by lebeck69** [Gifford47/HCPBridgeMqtt#69]
Thx a lot for the huge work and precise installation procedure

The issue I have is when selecting ESP Model in platformio.
instruction says 

> ## Build and Flash
> 
> Go back to the Platform IO UI and click on the ESP Model you got under "Project Tasks".
> ESP32 for older Boards and ESP32S3 for newer Boards (for example all PCBs with a Tynet logo)
> Open the General Tasks of the Board you got and click Build.

but i don't have 'simple esp32s3' so i tryed to pick esp32s3_tynet (i bought the tynet board)

But then i have the following error 

> UnknownPackageError: Could not find the package with 'espressif/toolchain-riscv32-esp @ 8.4.0+2021r2-patch3' requirements for your system 'windows_amd64'

I thus googled and found this : 

Please add the following line into the [env] section in the platformio.ini:

> [env]
> platform_packages = toolchain-riscv32-esp @ 8.4.0+2021r2-patch5

    
After adding this line all seems fine : Project has been successfully updated!

Have i done something wrong ?
Have some one else had the same issue ?

**Comment by Tysonpower** [comment]
never had this issue, i don't think you need this line but rather clean and reconfig the project after cloning from git.

**Comment by lebeck69** [comment]
> never had this issue, i don't think you need this line but rather clean and reconfig the project after cloning from git.

I manage to reach webui and all worked fine.
Problem can be close.
I might be very bad with platformui ;)

Thx again for you board
