### ISSUE TITLE
Support Client ID for MQTT connection

### ISSUE THREAD

**Issue by Autonoma-Bauernfeind** [Gifford47/HCPBridgeMqtt#72]
**Is your feature request related to a problem? Please describe.**
In the MQTT definition a client ID shall be provided. Also a lot of MQTT broker need a unique Client ID to be able to connect-

**Describe the solution you'd like**
An additional field or using the already existing field Device ID as client ID?

**Describe alternatives you've considered**
There is no alternative to that

**Comment by Gifford47** [comment]
hi!
it´s in the current dev branch, see #71 . i`ll merge it into master soon.

**Comment by Tysonpower** [comment]
@Autonoma-Bauernfeind the ID_LENGTH is not defined in the config, what should be the default value for that?

**Comment by Gifford47** [comment]
ok, my configuration wasn't merged, sry. the length could be 16 chars. Do you push a tested PR?

**Comment by Tysonpower** [comment]
no didn't do a pr, just hardcoded it locally so i can build, so feel free to push your config
