### ISSUE TITLE
Add/Show Firmware-Version somewhere

### ISSUE THREAD

**Issue by webflash-aj** [Gifford47/HCPBridgeMqtt#89]
The installed Version of the Firmware should be visible somewhere in the WebGUI.

**Comment by Tysonpower** [comment]
Updated in my Fork, it's avaliable in the webui under the /sysinfo url.

https://github.com/Tysonpower/HCPBridgeMqtt_tynet

**Comment by Gifford47** [comment]
also updated in current [dev](https://github.com/Gifford47/HCPBridgeMqtt/tree/development)
