### ISSUE TITLE
AsyncElegantOTA to ElegantOTA

### ISSUE THREAD

**Issue by Max-Github84** [Gifford47/HCPBridgeMqtt#91]
AsyncElegantOTA has been deprecated and it is NOT recommended for usage. Please consider migrating to [ElegantOTA](https://github.com/ayushsharma82/ElegantOTA) which now comes with async mode. Learn More on async mode: https://docs.elegantota.pro/async-mode/

If I want to compile the platformio project I get some errors because of the AsyncElegantOTA.
I tried to change to the new version, but my skills are not good enough yet...

**Comment by Tysonpower** [comment]
Updated it in my Fork: https://github.com/Tysonpower/HCPBridgeMqtt_tynet

**Comment by Gifford47** [comment]
also updated in current [dev](https://github.com/Gifford47/HCPBridgeMqtt/tree/development)
