### ISSUE TITLE
Invalid packets are sent to MQTT

### ISSUE THREAD

**Issue by alexnederlof** [Gifford47/HCPBridgeMqtt#97]
**Describe the bug**
- Device marks its MQTT as offline
- Availability on MQTT is therefore also set to false

My Mosquitto server says (in a loop):

```
  452705: New client connected from 10.42.0.0:43537 as ESP-18114243CA48 (p2, c1, k15, u'gate').                                                                                                                
  1732452710: Client ESP-18114243CA48 disconnected due to malformed packet.                                                                                                                                          
  1732452723: New client connected from 10.42.0.0:54130 as ESP-18114243CA48 (p2, c1, k15, u'gate').                                                                                                                 
  1732452725: Client ESP-18114243CA48 disconnected due to malformed packet.                                                                                                                                          
  1732452730: New client connected from 10.42.0.0:47305 as ESP-18114243CA48 (p2, c1, k15, u'gate').                                                                                                                
  1732452733: Client ESP-18114243CA48 disconnected due to malformed packet.                                                                                                                                          
```

**To Reproduce**
1. Which motor do you have? Supramatic E4
2. Which branch/release did you use? Version 0.0.7.1
3. Which peripherals (bme280, HCsr04, ...)  [RS485 Bridge - DIY Hörmann MQTT Adapter - ESP32-S3 Dev Board](https://shop.tynet.eu/en/)

**Expected behavior**
Stable connection to MQTT

**Comment by Gifford47** [comment]
can't reproduce it. It seems that's another client or saftware, isn't it?

**Comment by alexnederlof** [comment]
Yes, I opened on the wrong repo, sorry. Needed to be https://github.com/Tysonpower/HCPBridgeMqtt_tynet

**Comment by machine-bit** [comment]
I am getting this same issue @Gifford47 on the board you have sent me. It’s not detecting the device in Home Assistant either 

![Image](https://github.com/user-attachments/assets/d5bdc857-e641-41cf-b469-3f0f5a3874a2)

**Comment by Gifford47** [comment]
Please enable verbosity level to debug and resend log on connect

**Comment by Tysonpower** [comment]
> I am getting this same issue [@Gifford47](https://github.com/Gifford47) on the board you have sent me. It’s not detecting the device in Home Assistant either
> 
> ![Image](https://github.com/user-attachments/assets/d5bdc857-e641-41cf-b469-3f0f5a3874a2)

Check if your DeviceID is to long, MQTT doesent like IDs that are too long. But verbosity level in the log could help as well to understand the issue better as gifford mentioned.

**Comment by Tysonpower** [comment]
> [@Tysonpower](https://github.com/Tysonpower) I did try and shorten the deviceid, but maybe not enough. It seems a bit happier in the logs, just need to wait for it to show up in auto discovery now. Thanks

If HA doesent find it but in MQTT it shows up correctly maybe restart HA to make auto discovery happy again :)
